// Legacy public mail relay intentionally retired. Signup notification is owned
// by the protected registration workflow so arbitrary callers cannot send mail.
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

serve(() =>
  new Response(
    JSON.stringify({
      error: "ENDPOINT_RETIRED",
      message: "Signup notifications are generated by the backend.",
    }),
    {
      status: 410,
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": "no-store",
      },
    },
  ),
);
