import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/Reveal";
import { Users, FileText, ShieldAlert } from "lucide-react";
import { Link } from "react-router-dom";

const totalMembersSections = [
  {
    title: "A",
    names: [
      "Abalos Lemos, Ana Claudia",
      "Abero Cassanello, Sebastian",
      "Aborigen Olivera, Walter",
      "Abreu, Juan Sebastian",
      "Abril, Maria Julia",
      "Acosta, Kevin",
      "Acosta, Mauricio",
      "Acosta Campanella, Ximena",
      "Aguerre Jimenez, Macarena",
      "Aguiar Farina, Juan Ignacio",
      "Aharonian, Pablo",
      "Ahedo, Anibal",
      "Ahlig, Kurt",
      "Aintablian, Gabriel",
      "Alaniz, Anibal",
      "Albornoz Viera, Sofia Mercedes",
      "Almansa, Andres",
      "Alonso, Diego",
      "Alonso, Federico",
      "Alonso Chinepe, Miguel",
      "Alonso, Pablo",
      "Alonso, Santiago",
      "Alonso, Sebastian",
      "Altamiranda, Carlos",
      "Altamiranda, Eduardo",
      "Alterwain, Andres",
      "Almendras, Denise",
      "Alvarez, Maria Victoria",
      "Alvarez, Martin",
      "Alvarez Montenegro, Nerea",
      "Alvarez, Nicolas",
      "Amendola Arcari, Leonardo",
      "Amoza Irigoyen, Daniel",
      "Andino, Paula",
      "Andreatta, Guzman",
      "Andreatta, Ignacio",
      "Antelo, Santiago",
      "Aramis",
      "Arbulo Schiavone, Lucia",
      "Ares Pavan, Florencio",
      "Arrascaeta Garcia, Marcela",
      "Arrascaeta, Serrana",
      "Arroyo, Alejandro",
      "Arroyo, Victor",
      "Artigas Musitelli, Carlos Marcelo",
      "Artigas Soria, Agustin Maximiliano",
      "Asi, Guillermo",
      "Astigarraga, Martin",
      "Azzarini, Hugo",
    ],
  },
  {
    title: "B",
    names: [
      "Baccino, Cecilia",
      "Baccino, Gaston",
      "Baccino, Martin",
      "Badaro Salom, Felipe Santiago",
      "Bafundo Bartellone, Fiorella",
      "Ballestero, Patricia",
      "Banegas, Maite",
      "Banales Meharu Pablo",
      "Banales Meneghetti, Federico",
      "Banales Meneghetti, Ignacio",
      "Banales Meneghetti, Pablo",
      "Banales, Pablo IN MEMORIAM",
      "Barcelo , Edison",
      "Barcelo Koser, Marcel",
      "Barcelo, Gerti",
      "Barcelo, Ing.",
      "Barran Chianella, Nicolas Andres",
      "Barreiro, Eric",
      "Barreneche Abril, Javier IN MEMORIAM",
      "Barreneche Abril, Omar",
      "Barreneche Castel, Omar",
      "Barreneche Sarasola, Gabriel",
      "Barreneche Sarasola, Juan Manuel",
      "Barreneche Specht, Alicia",
      "Barreneche Specht, Bianca",
      "Barreneche Specht, Estibaliz",
      "Barreneche Specht, Mathias",
      "Barreto Acosta, Jocelin",
      "Bartellone Miranda, Marcela",
      "Basani Patel, Pietro",
      "Basani Patel, Radha",
      "Bassi Dresti, Eduardo IN MEMORIAM",
      "Baumfeld Bernheim, Brigida",
      "Baumfeld Reiman, Alexander IN MEMORIAM",
      "Bautista Gonzalez, Angel IN MEMORIAM",
      "Bazzano, Luis",
      "Beitler, Rosy",
      "Bellbe Gil, Camila",
      "Bellbe Gil, Sofia",
      "Bello Fernandez, Joaquin",
      "Bello Kegel, Sebastian",
      "Bello, Gaston",
      "Benenati Rodriguez, Jessica",
      "Benitez Odella, Pilar Zoe",
      "Benko Sorbello, Matias Astilla",
      "Benitez Sturla, Florencia",
      "Benitez, Magdalena",
      "Bentacor, Natalia",
      "Bentos Salazar, Benjamin Cesar",
      "Beraza, Javier",
      "Beraza, Lourdes",
      "Berger Ledesma, Lilly Zoe",
      "Berger Ledesma, Lucila",
      "Bermejo, Diego",
      "Berriel, Raul",
      "Berthet Steverlinck, Alicia",
      "Bertiz Ghisolfo, Mariana",
      "Bertiz Ghisolfo, Romina",
      "Biatturi Garcia, Jorge Andres",
      "Biatturi Garcia, Paola",
      "Biatturi, Francisco",
      "Bibbo Barboza, Mauro",
      "Blanco Caitano, Yanina Tamara",
      "Blanco, Beatriz",
      "Blassi Mazioti, Edison",
      "Blassi Mazioti, Milton",
      "Blengini, Aldo",
      "Bolioli Caunegre, Manuel Agustin",
      "Bolioli Caunegre, Joaquin",
      "Bonacchi Panzera, Juan Jose",
      "Bonifacino Kastner, Aldo",
      "Bonifacino, Mateo",
      "Bonnahon Fournier, Santino",
      "Bonnefon, Pablo",
      "Bottarelli Arenas, Valetino Roberto",
      "Borda Gonzalez, Karina Lucia",
      "Borotra, Carlos",
      "Boudinet, Danny",
      "Boudinet, Michel",
      "Boudette Rozas, Maria Isabel",
      "Bove Ramirez, Maria Noel",
      "Britos, Alen",
      "Broglioli Saralegui, Agustin",
      "Brondo Varela, Jessica",
      "Brun, Sebastian",
      "Burcci, Carlos",
    ],
  },
  {
    title: "C",
    names: [
      "Caballero Gomez, Lucia",
      "Cabrera, Alejandro",
      "Cabrera, Hermyr",
      "Cabrera, Yessi",
      "Caceres Gonzalez, Paula",
      "Caiafa, Flavio",
      "Caiafa, Marcelo",
      "Camacho Ramos, Raquel",
      "Camacho Reyno, Hector IN MEMORIAM",
      "Cammarota, Armando",
      "Cammarota, Daniel",
      "Cammarota, Virginia",
      "Canale Paredes, Luis Alberto",
      "Cancela Gonzalez, Maria Belen",
      "Canepa, Ana Lia",
      "Canepa Hernandez, Sharon Anne",
      "Canepa, Sandra",
      "Capeluto, Sofia",
      "Cardozo, Walter",
      "Carlotto de Lemos, Luciano",
      "Carminatti, Brian",
      "Carmona Sarniguet, Leonardo Andres",
      "Casariego Zuniga, Alejandro",
      "Casas, Santiago",
      "Castello, Ariel",
      "Castello, Camila",
      "Castillo, Natalia",
      "Castro Navia, Juan Pablo",
      "Cedres, Emiliano",
      "Cesaro, Daiana",
      "Chagas, Sergio",
      "Chaves Pineyro, Ana",
      "Chaves Pineyro, Lucia",
      "Chaves, Luis",
      "Chicheff, Monserrat",
      "Chimenz Ferreira, Edgar Fernando",
      "Cladera Grecco, Jose IN MEMORIAM",
      "Clara Dalldorf, Mario",
      "Clara Rodriguez, Felipe",
      "Clara Mayado, Ana Julia",
      "Clara Mayado, German Mathias",
      "Clara Mayado, Ignacio Martin",
      "Clavijo, Martin",
      "Clavijo, Pablo",
      "Clavijo, Rodrigo",
      "Clement Lindmayer, Alfredo",
      "Clement Lindmayer, Guillermo",
      "Clement Lindmayer, Martin Ernesto IN MEMORIAM",
      "Clement, Gunther",
      "Cocco Bonacchi, Julieta Romina",
      "Coitinho Sosa, Alvaro Damian",
      "Coitinho Sosa, Leonel Heber",
      "Colina Callejas, Maria Victoria",
      "Conde, Santiago",
      "Cordoba, Martin",
      "Coronel Aires, Brinna Aylen",
      "Correa, Agustin",
      "Correa, Rocio",
      "Correia Pallozzi, Alejandro",
      "Correia Pallozzi, Leonardo",
      "Correia, Wilde",
      "Coude Rey, Alexis Joaquin",
      "Cova, Graciela",
      "Cova Mazzei, Nicolas",
      "Cova, Maria Jose",
      "Croci Pasina, Olivia",
      "Cruz, Daniel",
      "Cuello, Bruno",
      "Cuello, Damian",
      "Cuello, Daniel",
      "Cuenca Cappetta, Sofia",
      "Curcho, Luis",
      "Custodio, Mario",
      "Custodio, Ricardo",
      "Custodio, Rosina",
    ],
  },
  {
    title: "D",
    names: [
      "D'Acosta Cabral, Ruben IN MEMORIAM",
      "D. Oliveri, Adriana",
      "Da Rosa, Matias Maximiliano",
      "Da Silva, Carolina",
      "Dalbora, Fernando",
      "Dambrosio Peri, Gianina",
      "Dambrosio Peri, Noelia",
      "Davies Pertzel, Sheila",
      "Daz Silva, Noelia Beatriz",
      "De Armas, Fabiana",
      "De Armas Caprile, Sabrina",
      "De Cuadro {en la Patrulla Adler en el 71}",
      "De Brun, Raul",
      "De Costales, M. G.",
      "De la Vega Ramos, Juan Ignacio",
      "De Leon Polkman, Jaron Damian",
      "De Los Santos Deus, Agustin Enrique",
      "De Los Santos Deus, Ximena Eliana",
      "De Los Santos Nieves, Alberto",
      "De Los Santos Nieves, Carlos",
      "De Los Santos Nieves, Luis Antonio",
      "De Los Santos Quiroga, Alma Magdalena",
      "De Los Santos, Sandino",
      "De Ocampo, Gonzalo",
      "De Olivera Bueno, Nicolas",
      "De Palleja, Pablo",
      "De Valli, Luis",
      "Dearce, Carolina",
      "Debrassi Silva, Luca",
      "Debrassi Silva, Renzo",
      "Debellis, Andrea",
      "Debellis, Antonella",
      "Debellis, Carlos",
      "Debellis, Fiorella",
      "Decia Cairo, Ignacio Ismael",
      "Del Bo,",
      "Del Castillo Morales, Paulina",
      "Del Valle, Gustavo",
      "Delfin, Daniel",
      "D'Elia, Mario Luis",
      "Denis, Daniela",
      "Depaoli, Matias",
      "Depaoli, Rodrigo",
      "Dibello, Carlos",
      "Dibello, William",
      "Diaz Burgueno, Maria Victoria",
      "Diaz Calixto, Alexandra",
      "Diaz Silva, Fiorela Anabel",
      "Diaz, Alejandro",
      "Dix, Gerhard",
      "Do Carmo Fiedler, Daniel",
      "Do Carmo Fiedler, Javier",
      "Dorwald, F.",
      "Dr. Hampe,",
      "Duarte, Carlos",
      "Duarte Lemos, Leticia",
      "Duarte, Zoe",
      "Dubra, Mathias",
      "Dubra, Patricia",
      "Duce, Romina",
      "Duran, Edgardo",
      "Duran, Federico",
      "Duran, Jacinto",
      "Duran, Javier",
      "Duve Puente, Romina Antonella",
    ],
  },
  {
    title: "E",
    names: [
      "Echarte Raffaelli, Sebastain Luis Carlos",
      "Echenique, Bruno",
      "Echevarria de Leon, Luis",
      "Emirkanian, Juan",
      "Enciso, Sofia",
      "Engelhardt, Maximo",
      "Engelhardt Chifflet, Guillermo",
      "Engelhardt Chifflet, Federico",
      "Escobar La Palma, Dana Jasmin",
      "Esmoris, Romina",
      "Espinosa Etchebarne, Lucas",
      "Espinosa Etchebarne, Martin",
      "Espinosa Etchebarne, Matias",
      "Espinosa, Oscar",
      "Esposito, Claudia",
      "Estrada, Evelyn",
      "Estrada, Marcela",
    ],
  },
  {
    title: "F",
    names: [
      "Fabini, Santiago",
      "Faccelo, Lucas",
      "Faget Yrm, Emma",
      "Falero, Silvio",
      "Faluotico,",
      "Fantin, Daniel",
      "Farias {en la Patrulla Buffel en el 71}",
      "Farina Pereyra, Agustina",
      "Farina, Esteban",
      "Fastoso, Fernando",
      "Fau, Jose Alberto",
      "Fernandez, Aldo",
      "Fernandez Botta, Cecilia",
      "Fernandez Rouco, Horacio",
      "Ferrand, Alexis IN MEMORIAM",
      "Ferrand, Karl",
      "Ferrari, Gustavo",
      "Ferrari, Andrea Giselle",
      "Fidalgo Diaz, Jaime Daniel",
      "Fidalgo Diaz, Miguel",
      "Fiori Flores, Bruno Andres",
      "Fleischer De Vita, Bruno Nicolas",
      "Fleischer, Eduardo",
      "Fleitas Maldonado, Emilia Pia",
      "Florines, Alberto",
      "Florines, Claudio",
      "Florines, Silvio",
      "Florines, Silvio (padre)",
      "Fonsalia Rodriguez, Gustavo Enrique",
      "Fontes, Javier",
      "Franquez, Roberto",
      "Fratti Artia, Simon",
      "Fullana Chub, Isabela",
      "Funes Migliarini, Carina Beatriz",
      "Funes Migliarini, Gustavo Adrian",
      "Funes Migliarini, Rodrigo Juan",
      "Funes, Gustavo",
      "Funes, Rodrigo",
      "Funes, Nicole",
      "Furtado, Carlos",
      "Furtado Santana, Catalina",
    ],
  },
  {
    title: "G",
    names: [
      "Gadea Foscaldi, Lucia",
      "Gaggero Dallo, Mauricio",
      "Gago, Vanessa",
      "Galarza Lopetegui, Juan Pedro",
      "Galasso, Juan",
      "Galliano Mazzoni, Federico Ignacio",
      "Gallinares Testoni, Alejandro",
      "Galloso Solari, Guillermo",
      "Galvan, Maria del Carmen",
      "Galvan, Miguel",
      "Ganss, Peter",
      "Garaycochea Pais, Valentina",
      "Garcia Bentos, Mauricio Alejandro",
      "Garcia Fontes, Alfredo",
      "Garcia Fontes, Walter",
      "Garcia Pollini, Sabrina Paola",
      "Garcia Balsamo, Belen",
      "Garcia, Federico",
      "Garcia, Fernando",
      "Garcia Uyterhoeven, Gael",
      "Garcia, Gaspar",
      "Garcia, Gustavo (Gustavito)",
      "Garcia, Marcos",
      "Garcia, W.",
      "Garrido Garcia, Martin Gonzalo",
      "Gasperini, Luis",
      "Gastellu Varela, Michel Rodrigo",
      "Gato, Pedro",
      "Gazzo Cazot, Julio IN MEMORIAM",
      "Georgalis Lopez, Cecilia",
      "Georgalis Lopez, Leticia",
      "Geretta, Humberto D.",
      "Gerhard Klockner, Camilo Norbert",
      "Gerhard Klockner, Daniel Simon",
      "Gerhard Klockner, Myriam Libertad",
      "Gerhard Otero, Jorge Adan",
      "Giles Fau, Agustin",
      "Glisenti Perez, Enzo",
      "Goimil Tortora, Luciana",
      "Goloubintseff, Ivan",
      "Gomez Garrett, Guillermo",
      "Gomez, Maria Victoria",
      "Gonzales Salvarrey, Anaiis",
      "Gonzales, Christian",
      "Gonzales, Justino",
      "Gonzalez, Joaquin",
      "Gonzalez Brondo, Carolina Florencia",
      "Gonzalez Reyno, Hector IN MEMORIAM",
      "Gonzalez, Luis",
      "Gonzalez, Mariana",
      "Gonzalez, Mathias",
      "Gonzalez Moraes, Nicolas Emiliano",
      "Gordon Filing, Nicholas",
      "Grunert Lopez, Eduardo",
      "Grunert Lopez, Jorge",
      "Grunwald, Bruno",
      "Grunwald, Federico",
      "Grunwald, Juan",
      "Guecaimburu Anton, Fernanda",
      "Guerequiz, Augusto Valentin",
      "Guevara, Ernesto",
      "Guimaraens Corrochano, Gonzalo Javier",
    ],
  },
  {
    title: "H",
    names: [
      "Hartschuh, Ernst",
      "Hays, Hugh",
      "Hein Ferrari, Matilde",
      "Hein Heberling, Elsa",
      "Hein Heberling, Ricardo",
      "Hein Peri, Adrian",
      "Hein Peri, Valeria",
      "Hein, German",
      "Hein, Paul",
      "Hellebronth, Dieter",
      "Hernandez Buzzi, Diego",
      "Hernandez Ferretjans, Hebert",
      "Hernandez Ferretjans, Luis",
      "Hernandez Ferretjans, Pablo",
      "Hernandez Olivera, Santiago Nicolas",
      "Hernandez, Diego",
      "Hernandez, Gabriel",
      "Hernandez, Luis",
      "Hernandez, Natalia",
      "Hernandez, Raul",
      "Hernandorena, Diego",
      "Herrera Luciaro, Carollna",
      "Herrera Luciaro, Maria Agustina",
      "Herrera, Pablo",
      "Holm Longo, Maria Cristina",
      "Holm, Sandra",
      "Horne, Ignacio",
      "Huber, Patricia",
    ],
  },
  {
    title: "I",
    names: [
      "Ibarra Paterno, Jose",
      "Infante de Frankestein, Olga",
      "Introini, Alfredo",
      "Invernizzi, Claudio",
      "Invernizzi, Enrique",
      "Issa Aristegui, Jamil",
    ],
  },
  {
    title: "J",
    names: [],
  },
  {
    title: "K",
    names: ["Kalmer, Ernesto", "Klimenco, Gisela", "Kohler, Heinz", "Kunze, Kard"],
  },
  {
    title: "L",
    names: [
      "Labrador, Emilia",
      "Lacava Curcella, Maite Stephani",
      "Lacava, Jorge",
      "Lacava, Miguel",
      "Lamela, Claudia",
      "Lamela, Pablo",
      "Landone, R.",
      "Lapi, Rominna",
      "Lapi, Silvana",
      "Larraura, Jose",
      "Larsen, Peter",
      "Lasa, Juan Jose",
      "Laureano, Diego",
      "Lauterstein, Tomas",
      "Lecour Olivera, Leopoldo Hernan",
      "Lema, Lucia",
      "Lema, Noelia",
      "Leniani, Albana",
      "Lens, Cecilia",
      "Levin, Manuel",
      "Levy, Ricardo",
      "Levy, Sra.",
      "Liber Barboza, Ernesto",
      "Libisch, Gabriela",
      "Lieschke, Roberto",
      "Liguori, Maria Eugenia",
      "Lindmayer, Andres",
      "Llagarias Belluomini, Mario Cesar Filadelfo",
      "Llanes Bat, Eduardo",
      "Llanes Bat, Fabiana",
      "Llanes Bat, Javier",
      "Lobl, Enrique H.",
      "Lobl, Jorge",
      "Lodigiani Bargioni, Patricia",
      "Lodigiani Bargioni, Roberto",
      "Lodigiani Francis, Andrea",
      "Lois Perez, Gonzalo Federico",
      "Lopez, Jorge",
      "Lopez, Juan Carlos",
      "Lopez Leivas, Javier",
      "Lopez Lopez, Lucia",
      "Lopez Lopez, Mateo",
      "Lopez Miles, Florencia",
      "Lopez Muino, Thiago",
      "Lopez Roig, Allison",
      "Lopez Roig, Diego",
      "Lopez Ojeda, Valeria",
      "Lopi, Romina",
      "Lorenzo Dreyer, Felipe",
      "Lorenzo Dreyer, Ignacio",
      "Lorenzo Dreyer, Santiago",
      "Lorenzo Gomes, Carlo Adrian",
      "Lorenzo Gomes, Javier Hugo",
      "Lorenzo Holm, Virginia",
      "Lorenzo Pardozo, Julieta",
      "Lorenzo Rachmeier, Marina",
      "Lorenzo Restano, Ernesto Tabare",
      "Lorenzo Restano, Luis Guzman",
      "Lorenzo Restano, Martin",
      "Lorenzo Restano, Nora",
      "Lorenzo Roldan, Florencia",
      "Lorenzo Roldan, Francisco",
      "Lorenzo Romano, Camila",
      "Lorenzo Silveira, Maria Belem",
      "Lorenzo Silveira, Pia",
      "Lostao, Eduardo",
      "Lucas, Joan",
      "Lucchi Corrales, Claudio",
      "Lugaro, Ricardo",
      "Lugaro, Rodolfo",
      "Luiguin,",
      "Luongo Zuceolo, Joaquin",
      "Luzardo, Alvaro",
      "Luzardo, Alejandro",
    ],
  },
  {
    title: "M",
    names: [
      "Machado Araujo, Vanina Sofia",
      "Machado Vignoles, Camilo",
      "Maciel, Javier",
      "Magallanes, Leonardo",
      "Magnabosco, Juan",
      "Maldonado, Emilia",
      "Malvido, Humberto",
      "Malvido, Rosana",
      "Malzone Vazquez, Mikaela",
      "Maneyro Acosta, Pilar",
      "Maneyro Acosta, Victoria",
      "Marasco Raposo, Valentina",
      "Mari, Jorge",
      "Marichal, Gaston",
      "Marmolejo, Marcelo",
      "Marquez, Leonardo IN MEMORIAM",
      "Martinez Martinez, Viana, Mabel",
      "Martinez Pereira, Juan Antonio",
      "Martinez Perez, Alvaro",
      "Martinez Perez, Pablo",
      "Martinez Perez, Patricia",
      "Martinez Perez, Rosana",
      "Martinez Plaz, Emiliano",
      "Martinez, (Pocho)",
      "Martinez, Damian",
      "Martinez, Graciela",
      "Martinez, Juan Ignacio",
      "Martoni, Eduardo",
      "Mato, Lucia",
      "Matontte Sanchez, Elias Benamin",
      "Mautone, Daniel",
      "Maverino, Sergio",
      "Mazorkevich Urban, Julieta",
      "Mazzeta Fernandez, Cecilia Maria",
      "Mazzei Ale, Josefina",
      "Mazzei Ale, Juan Sebastian",
      "McConney, Jennifer",
      "Medero, Samira",
      "Medina, Ana Maria",
      "Medina, Walter",
      "Meerhoff Miranda, Rodolfo Enrique",
      "Mendaro, Mauro",
      "Mendez Cal, Camilo",
      "Mendez, Maira",
      "Meneghetti, Silvia",
      "Menendez Irurueta, Agustin",
      "Menendez, Itzel",
      "Mendoza, Lucia",
      "Mercado, Gabriela",
      "Mieres, Alfonso",
      "Mieres, Ana Elena",
      "Mieres, Juan Jose",
      "Migliaccio Mattiauda, Julietta",
      "Milan, Francisco",
      "Milan, Gustavo IN MEMORIAM",
      "Miranda Fernandez, Mayra Lucia",
      "Miranda, Joaquin",
      "Mitfessel, Adriana",
      "Mitfessel, Bruno",
      "Mitfessel, Pablo",
      "Molini, Diego",
      "Montes Vegar, Maximiliano",
      "Morales, Marcelo",
      "Morales Novo, Camila Sofia",
      "Moreira, Bruno",
      "Moreira Pingaro, Noelia",
      "Moreira, Fiorella",
      "Moreira Nan, Mateo Nicolas",
      "Moreira, Jose",
      "Morelli, Rafael",
      "Muller, Wilhelm",
      "Munecas Louzao, Horacio IN MEMORIAM",
      "Munoz, Juan A.",
      "Murias, Ignacio",
      "Muse, Magdalena",
    ],
  },
  {
    title: "N",
    names: [
      "Nalerio, Pablo",
      "Navarro Carracelas, Mauricio",
      "Nicoloff, Benjamin",
      "Noguera Rodriguez, Camila Lorena",
      "Notaro, Fernando",
      "Nuñez, Juan Angel",
      "Nuñez, Nicolas",
      "Nuñez San Remo, Maria",
    ],
  },
  {
    title: "O",
    names: [
      "Oficialdegui, Sebastian",
      "Ojeda, Devora",
      "Ojeda, Pablo",
      "Olagharay Paladino, Lucia",
      "Olazabal Acuna, Michelle",
      "Olbertz, Martin",
      "Olij Passanante, Natalia",
      "Olij Passanante, Virginia",
      "Olij, Johannes",
      "Olivera, Gabriel",
      "Olivera, Lucia",
      "Olivera, Marco",
      "Olivera, Walter",
      "Oliveri Sales, Valentina Fiorella",
      "Oliveri Correia, Atilio Luis",
      "Olmos Dos Santos, Jean Franco",
      "Onnen, Engelbert",
      "Orlando Chifflet, Carolina",
      "Orlando Chifflet, Luis",
      "Orlando Chifflet, Martin",
      "Orlando Chifflet, Victor Manuel",
      "Orlando Hein, Martina",
      "Orlando Hein, Valentina",
      "Orlando, Lionel",
      "Orlando Martinez, Alethia",
      "Orlando Martinez, Flavio",
      "Orlando Martinez, Glauco",
      "Orlando Martinez, Marcia",
      "Ortelli Perez, Erika Gianinna",
      "Ortiz, Camila",
      "Ortiz, Mateo",
      "Osano, Julio",
      "Osta Ortega, Federico",
      "Osta Ortega, Julian",
      "Ostoic De Leon, Alexei",
      "Ostoic De Leon, Vladimir",
      "Otanha Suna, Maria Alejandra",
      "Otanha, Andrea",
      "Otermin, Rodrigo",
      "Ouvina, Rafael",
      "Oviedo Rodriguez, Natalia",
    ],
  },
  {
    title: "P",
    names: [
      "Pagola, Juan Manuel",
      "Paiva Rey, Federico Gaston",
      "Paiva Rey, Mathias Nicolas",
      "Pallares Otanha, Rodrigo",
      "Pallares, Alvaro",
      "Pallozzi Gerpott, Stefan",
      "Pallozzi Gerpott, Renata",
      "Paredes Velazquez, Maximiliano",
      "Parrillo, Nelson",
      "Passanante DeGiuli, Laura",
      "Pasquet, Nicolas",
      "Pastrana, Alfredo",
      "Pastrana, Fernando",
      "Pastre Calvetti, Sabrina",
      "Paulis, Raul",
      "Pedrini Fein, Fabiana",
      "Pedrini Fein, Giancarlo",
      "Peluffo, Pablo",
      "Pena, Francisco",
      "Pena Fullana, Joaquin",
      "Pena, Juan Pedro",
      "Percovich Novaro, Candela",
      "Pereira Pierce, Alan",
      "Pereira Pierce, Daniel",
      "Pereira, Victor",
      "Perera Lopez, Florencia Matilde",
      "Perera Lopez, Maia Victoria",
      "Pereyra Heberling, Maria Ines",
      "Pereyra, Enrique",
      "Pereyra Fernandez, Juan Mateo",
      "Perez Lopez, Facundo",
      "Perez Mabel (Mama Martinez)",
      "Perez Farina, Micaela",
      "Perez Seoane, Jimena",
      "Perez Seoane, Pablo Francisco",
      "Perez, Nicolas",
      "Perez, Richard",
      "Perez, Sebastian",
      "Perez, Victoria",
      "Perg Aristegui, Benjamin Martino",
      "Perg Aristegui, Ian Benicio",
      "Peri Monge, Silvia",
      "Peri Monge, Patricia",
      "Perone Mercado, Diego",
      "Perone Mercado, Erika",
      "Pierce, Maureen",
      "Perugoria, Fabian",
      "Pies, Federico",
      "Pinelli Bianchi, Bernardita",
      "Pinelli Bianchi, David",
      "Pini Otero, Nahuel",
      "Pissarouk Rizzolo, Damian",
      "Pissarouk Rizzolo, Vladimir",
      "Pissarouk Ferrada, Vladimir",
      "Podesta, Carlos",
      "Porras Maieli, Lucia",
      "Porro Rodriguez, Renzo",
      "Porta Mulattieri, Juan Jose IN MEMORIAM",
      "Posada, Nicolas",
      "Pose, Jose Antonio",
      "Pose Azzarini, Diego Felipe IN MEMORIAM",
      "Pose Veirano, Santiago",
      "Pouquette Siri, Cecilia",
      "Poy Vasquez, Juan Sebastian",
      "Pozzo Picun, Adrian",
      "Pozzo Picun, Mauro German",
      "Pozzo Picun, Rodrigo",
      "Prato, Luis",
      "Prebetoni, Nelson",
      "Presto, Alejandro",
      "Presto, Jorge",
      "Presto, Jorge (Sr.)",
      "Prieto de Gimenez, Delia",
      "Punciolo, Fiorella",
      "Punciolo, Lorena",
      "Punciolo, Silvana",
      "Puyo, Raul",
    ],
  },
  {
    title: "Q",
    names: [
      "Quagliata {en la Patrulla Buffel en el 71}",
      "Quincke, Johanna",
      "Quinones, Marcelo",
      "Quinteros, Alberto",
    ],
  },
  {
    title: "R",
    names: [
      "Raggio, Santino",
      "Ramos Pose, Lucia",
      "Ramos Pinelli, Nara",
      "Ramos Scanegatti, Cristian Martin",
      "Rappalini, Pablo",
      "Rauhut Andress, Edgar IN MEMORIAM",
      "Rauhut Andress, Gert",
      "Rauhut Andress, Helga",
      "Razzetti Gomez, Marcos",
      "Razzetti Gomez, Tania",
      "Rebollo Panuncio, Maria Ines",
      "Regina, Pablo",
      "Regueiro, Oscar",
      "Reinolds Velazquez, Patricia",
      "Rey Rios, Marcos Fabian",
      "Ribeiro, Nicolas",
      "Rios Bolioli, Martina",
      "Rios, Emilia",
      "Riveiro Bello, Victoria Soledad",
      "Rivero Viera, Paula Luciana",
      "Rivero, Maria Eugenia",
      "Rivero, Esteban",
      "Rizzolo, Nelly",
      "Robaina Otanha, Emilia",
      "Rode, Claudia",
      "Rode, Claudio",
      "Rodriguez Bolioli, Maria Soledad",
      "Rodriguez Galloso, Valeria Stefania",
      "Rodriguez Guzman, Manuela",
      "Rodriguez Lezama, Felipe",
      "Rodriguez Revello, Gaston Manuel",
      "Rodriguez Silva, Analia Beatriz",
      "Rodriguez Silva, Facundo",
      "Rodriguez Toma, Gualberto",
      "Rodriguez Velazquez, Gonzalo Federico",
      "Rodriguez, Agustin",
      "Rodriguez, Alvaro",
      "Rodriguez, Diego",
      "Rodriguez, Carlos",
      "Rodriguez, Enrique",
      "Rodriguez Leguizamon, Julieta",
      "Rodriguez, Lautaro",
      "Rodriguez, Luciana",
      "Rodriguez, Matias",
      "Rodriguez, Maximiliano",
      "Rodriguez, Miguel",
      "Rodriguez Matto, Gimena",
      "Rodriguez Matto, Marcelo",
      "Rodriguez Matto, Veronica",
      "Rogido, Eugenio",
      "Romano Fabra, Natan",
      "Romang, Adrian",
      "Romang, Thomas",
      "Rosa Antunez, Monica",
      "Rose, Virginia",
      "Rosello, Nelson",
      "Rosenstiel, Axel",
      "Rosenstiel, Carlos E.",
      "Rosenstiel, Mellita",
      "Rosenstiel, Ricardo",
      "Rossi Conde, Francisco",
      "Rossi, Fabrizio",
      "Rossi, Rosina",
      "Rotunno Falchetti, Valeria",
      "Ruiz, Alfredo Gerardo",
      "Ruiz, Jose",
      "Rundie, Joaquin",
      "Russi Lorenzo, Lucas",
      "Russomando, Valentina",
    ],
  },
  {
    title: "S",
    names: [
      "Sacarelo, Federico",
      "Salamano, Duilio",
      "Salamano, Edgardo",
      "Salgado Mintegui, Macarena",
      "Salles Louro, Lucia",
      "San Martin, Emiliano",
      "San Martin, Gabriel",
      "San Martin, Leonardo",
      "San Martin, Pablo",
      "Sanchez, Karina",
      "Sanchez, Lucia",
      "Sanchez, Sandra",
      "Santana, Natalia",
      "Santoro Silva, Federico",
      "Santoro Silva, Fiorella Martina",
      "Santoro Silva, Sophia Stephani",
      "Santos Gonzales, Horacio Lautaro",
      "Santos, Manuel",
      "Sanz, David",
      "Sarmiento Arechederra, Julio Cesar IN MEMORIAM",
      "Sartorotti Dibello, Armando",
      "Sartorotti Dibello, Freddy",
      "Satriani, Karina",
      "Savio Cova, Nicolas",
      "Scaramuzzi, Cecilia",
      "Scarani Ballestero, Marccelo",
      "Scarani Ballestero, Sophia",
      "Schaaf, Peter IN MEMORIAM",
      "Schaffner Paez, Gabriel German",
      "Scheige, H.",
      "Schlief Jung, Juan",
      "Schmidt Lindmayer, Gertrudis Mariana",
      "Schmidt Lindmayer, Manfredo",
      "Schonburg, Ernesto",
      "Seade, Juan Sr.",
      "Seade, Juan",
      "Seade, Rocio",
      "Seade, Victoria",
      "Sergio {aparece en el Censo del 71 en la Patrulla Adler}",
      "Serralta Gascue, Juan Manuel",
      "Serrato, Vicky",
      "Serrato, Virginia",
      "Severi, Esteban",
      "Sfeir, Gonzalo",
      "Sica, Luis",
      "Sickinger Gonzalez, Reinardo Alfredo",
      "Sickinger Gonzalez, Elena",
      "Silavekz, Guido",
      "Silva Chiappini, Mateo",
      "Silva Rojas, Camilo",
      "Silva Velazquez, Diego German",
      "Silva Velazquez, Pablo",
      "Silva, Belen",
      "Silva, Benjamin",
      "Silva Gago, German Agustin",
      "Silva, Sofia",
      "Silveira, Andres",
      "Silveira, Ricardo",
      "Silvera Macaluso, Camila",
      "Silvera Saint Patour, Ana Belen",
      "Simeto, Cecilia",
      "Simeto Ferrari, Lucia",
      "Simeto, Sofia",
      "Simeto, Valentina",
      "Smircich, Emma",
      "Soca, Gonzalo",
      "Sola, Raul IN MEMORIAM",
      "Sola Etchemendy, Raul",
      "Sosa Hernandez, Ernesto",
      "Sosa Hernandez, Julieta",
      "Sosa Methol, Facundo",
      "Sosa Romero, Agustina",
      "Sosa Veiga, Maria Ximena",
      "Sommersguter, Manfred",
      "Souto, Valentina",
      "Spinelli Guedes, Nicole Emma",
      "Stanger, Claudia",
      "Stapf, Gustavo",
      "Stapff, Martin",
      "Stasienuk, Edgar",
      "Steinemann, Ulrich IN MEMORIAM",
      "Steverlinck, Enrique",
      "Strada, Evelyn",
      "Strada, Marcela",
      "Stratta, Jose Luis",
      "Strehl Pessina, Luisina",
      "Strehl Pessina, Matias",
      "Suna, Ana Laura",
      "Suna, Lucia",
      "Sutter, Peter",
    ],
  },
  {
    title: "T",
    names: [
      "Taglioretti, Miguel",
      "Talento Ing.",
      "Tambasco Marcelli, Maria Noel",
      "Tambasco Marcelli, Matias",
      "Tapia, Luis",
      "Tapia, Rodrigo",
      "Taramasso Vittola, Fabrizio",
      "Techera Fernandez, Alex Gustavo",
      "Techera Pascal, Julietta",
      "Techera Pascal, Mauro",
      "Techera, Sebastian",
      "Testoni Capelletti, Miguel",
      "Thomas Vinoles, Lorenzo Bautista",
      "Thrasivoulou, Alceo",
      "Torchiana, Javier",
      "Torrado Suarez, Emiliano",
      "Tort, Maria Ines",
      "Traba, Aylen",
      "Traba, Faustino",
      "Trasante, Tania",
      "Triunfo, Camila",
      "Trujillo, Carolina",
    ],
  },
  {
    title: "U",
    names: [
      "Ulloa, Javier",
      "Ulloa, Juan Manuel",
      "Urban, Julieta",
      "Urban, Valentina",
      "Urtasun, Pierina",
    ],
  },
  {
    title: "V",
    names: [
      "Valero Barreto, Abbie Lissel",
      "Varela, Enrique",
      "Veiga, Catalina",
      "Venier, Santino",
      "Veraza, Javier",
      "Verissimo, Paula",
      "Vernazza Taroco, Ana Lourdes",
      "Viera Mazzucchelli, Juan Pedro",
      "Viera, Noelia",
      "Viera Reyes, Sebastian Gonzalo",
      "Vilaplana Rosini, Abril",
      "Vilaplana Rosini, Anaclara",
      "Villasante, Mauricio",
      "Vitureira Aguirre, Martina",
      "Vitureira Aguirre, Agustina",
      "von Metzen, Sra. de",
      "von Zakrzewski, Bolko",
    ],
  },
  {
    title: "W",
    names: ["Walter, Miguel", "Weisskirch, Martin Olbertz"],
  },
  {
    title: "X",
    names: [],
  },
  {
    title: "Y",
    names: ["Yacosta, Estefania"],
  },
  {
    title: "Z",
    names: [
      "Zanolli, Marcelo",
      "Ziegler, Lucia",
      "Zsilavecz, Guido",
      "Zuniga Prego, Martin Diego",
    ],
  },
];

const vinculadosMembers = [
  "Bajac, Carlos",
  "Bauer, Maria Elena (esposa de Luis Lorenzo Gomez)",
  "Barcala, Silvia IN MEMORIAM",
  "Beare, Andrew (Andy)",
  "Belem, Yamandu",
  "Chaibun, Guillermo",
  "Coronel, Oribe",
  "Da Silva, Thais",
  "Dreyer, Gabriela",
  "Klimenko, Gisela",
  "Magnabosco",
  "Munecas Louzao, (hermana de Horacio Munecas)",
  "Leiro, Beatriz IN MEMORIAM",
  "Lodigiani Francis, Martha (esposa de Roberto Lodigiani)",
  "Linn, Roberto",
  "Roldan, Alicia (esposa de Martin Lorenzo)",
  "Romano, Gimena",
  "Russi, (marido de Nora Lorenzo Restano)",
  "Sequeira,",
  "Silveira, Maria Cecilia",
  "Steverlynck, Enrique IN MEMORIAM",
];

const Miembros = () => {
  return (
    <div className="min-h-screen">
      <section className="pt-24 sm:pt-28 md:pt-32 pb-10 sm:pb-14 bg-background/60 backdrop-blur-sm">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <Reveal className="max-w-4xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-muted/30 rounded-full mb-4">
              <Users className="w-4 h-4 text-primary" />
              <span className="text-primary font-semibold text-xs sm:text-sm">
                Archivo · Miembros y exmiembros
              </span>
            </div>
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              Lista de miembros y exmiembros
            </h1>
            <p className="text-sm sm:text-base md:text-lg text-muted-foreground leading-relaxed">
              Esta sección se publica con cuidado para respetar la privacidad y
              el consentimiento de las personas.
            </p>
          </Reveal>
        </div>
      </section>

      <section className="py-10 sm:py-14">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto space-y-6">
            <Reveal>
              <Card className="border-2 border-primary/20 shadow-lg bg-background/70 backdrop-blur-sm">
                <CardContent className="p-6 sm:p-8">
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 rounded-2xl bg-muted/30 flex items-center justify-center">
                      <ShieldAlert className="w-6 h-6 text-primary" />
                    </div>
                    <div className="flex-1">
                      <h2 className="text-xl sm:text-2xl font-semibold mb-2">
                        Publicación con consentimiento
                      </h2>
                      <p className="text-sm sm:text-base text-muted-foreground mb-4">
                        Antes de publicar datos personales, confirmamos la
                        autorización correspondiente. También podemos anonimizar
                        la información si es necesario.
                      </p>
                      <Badge variant="outline" className="bg-muted/30 text-primary border-primary/30">
                        Estado: en revisión de privacidad
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Reveal>

            <Reveal>
              <Card className="border-2 border-primary/20 shadow-lg bg-background/70 backdrop-blur-sm">
                <CardContent className="p-6 sm:p-8">
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 rounded-2xl bg-muted/30 flex items-center justify-center">
                      <FileText className="w-6 h-6 text-primary" />
                    </div>
                    <div className="flex-1">
                      <h2 className="text-xl sm:text-2xl font-semibold mb-2">
                        Enviar listados
                      </h2>
                      <p className="text-sm sm:text-base text-muted-foreground mb-4">
                        Si tenés listados históricos, enviálos y los organizamos
                        por secciones y años.
                      </p>
                      <Link to="/contacto">
                        <Button size="sm" className="gap-2">
                          <FileText className="w-4 h-4" />
                          Enviar material
                        </Button>
                      </Link>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Reveal>
          </div>
        </div>
      </section>

      <section className="py-10 sm:py-14 bg-background/60 backdrop-blur-sm">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-5xl mx-auto space-y-6">
            <Reveal>
              <Card className="border-2 border-primary/20 shadow-lg bg-background/70 backdrop-blur-sm">
                <CardContent className="p-6 sm:p-8">
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                    <div>
                      <h2 className="text-2xl sm:text-3xl font-semibold mb-2">
                        Miembros activos
                      </h2>
                      <p className="text-sm sm:text-base text-muted-foreground">
                        Listado en proceso de actualizacion y verificacion de
                        consentimiento.
                      </p>
                    </div>
                    <Badge variant="outline" className="bg-muted/30 text-primary border-primary/30">
                      Estado: en actualizacion
                    </Badge>
                  </div>
                </CardContent>
              </Card>
            </Reveal>
          </div>
        </div>
      </section>

      <section className="py-12 sm:py-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-5xl mx-auto space-y-6">
            <Reveal>
              <Card className="border-2 border-primary/20 shadow-lg bg-background/70 backdrop-blur-sm">
                <CardContent className="p-6 sm:p-8">
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-6">
                    <div>
                      <h2 className="text-2xl sm:text-3xl font-semibold mb-2">
                        Lista total de miembros y exmiembros
                      </h2>
                      <p className="text-sm sm:text-base text-muted-foreground">
                        Organizada por inicial del apellido.
                      </p>
                    </div>
                    <Badge variant="outline" className="bg-muted/30 text-primary border-primary/30">
                      Estado: consolidado
                    </Badge>
                  </div>

                  <div className="space-y-6">
                    {totalMembersSections.map((section) => (
                      <div key={section.title}>
                        <h3 className="text-lg sm:text-xl font-semibold mb-3">
                          {section.title}
                        </h3>
                        {section.names.length === 0 ? (
                          <p className="text-sm sm:text-base text-muted-foreground">
                            Sin registros.
                          </p>
                        ) : (
                          <ul className="grid gap-2 text-sm sm:text-base text-muted-foreground sm:grid-cols-2 lg:grid-cols-3">
                            {section.names.map((name) => (
                              <li key={`${section.title}-${name}`}>{name}</li>
                            ))}
                          </ul>
                        )}
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </Reveal>
          </div>
        </div>
      </section>

      <section className="py-12 sm:py-16 bg-background/60 backdrop-blur-sm">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-5xl mx-auto space-y-6">
            <Reveal>
              <Card className="border-2 border-primary/20 shadow-lg bg-background/70 backdrop-blur-sm">
                <CardContent className="p-6 sm:p-8">
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-6">
                    <div>
                      <h2 className="text-2xl sm:text-3xl font-semibold mb-2">
                        Vinculados al Septimo
                      </h2>
                      <p className="text-sm sm:text-base text-muted-foreground">
                        Personas relacionadas con la historia del grupo.
                      </p>
                    </div>
                    <Badge variant="outline" className="bg-muted/30 text-primary border-primary/30">
                      Estado: en revision
                    </Badge>
                  </div>

                  <ul className="grid gap-2 text-sm sm:text-base text-muted-foreground sm:grid-cols-2 lg:grid-cols-3">
                    {vinculadosMembers.map((name) => (
                      <li key={`vinculado-${name}`}>{name}</li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            </Reveal>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Miembros;

